--DWT层业务数据建表
--DWT层的建表思想和DWS层基本一致都是宽表的建表思想，每行数据代表一个维度在一定时间（1 、7、30天）内的累计行为，字段是根据
--维度表从DWS层的事实主题表进行二次聚合之后join到一张虚表，之后查询出所需字段插入到对应的维度事实表中。分区也是按照时间分区
--每个分区中存储的是截止当日的全量的维度对象的累计汇总行为


--建表语句
DROP TABLE IF EXISTS dwt_user_topic;
CREATE EXTERNAL TABLE dwt_user_topic
(
    `user_id`                               STRING COMMENT '用户id',
    `login_date_first`                      STRING COMMENT '首次活跃日期',
    `login_date_last`                       STRING COMMENT '末次活跃日期',
    `login_date_1d_count`                   STRING COMMENT '最近1日登录次数',
    `login_last_1d_day_count`               BIGINT COMMENT '最近1日登录天数',
    `login_last_7d_count`                   BIGINT COMMENT '最近7日登录次数',
    `login_last_7d_day_count`               BIGINT COMMENT '最近7日登录天数',
    `login_last_30d_count`                  BIGINT COMMENT '最近30日登录次数',
    `login_last_30d_day_count`              BIGINT COMMENT '最近30日登录天数',
    `login_count`                           BIGINT COMMENT '累积登录次数',
    `login_day_count`                       BIGINT COMMENT '累积登录天数',
    `order_date_first`                      STRING COMMENT '首次下单时间',
    `order_date_last`                       STRING COMMENT '末次下单时间',
    `order_last_1d_count`                   BIGINT COMMENT '最近1日下单次数',
    `order_activity_last_1d_count`          BIGINT COMMENT '最近1日订单参与活动次数',
    `order_activity_reduce_last_1d_amount`  DECIMAL(16, 2) COMMENT '最近1日订单减免金额(活动)',
    `order_coupon_last_1d_count`            BIGINT COMMENT '最近1日下单用券次数',
    `order_coupon_reduce_last_1d_amount`    DECIMAL(16, 2) COMMENT '最近1日订单减免金额(优惠券)',
    `order_last_1d_original_amount`         DECIMAL(16, 2) COMMENT '最近1日原始下单金额',
    `order_last_1d_final_amount`            DECIMAL(16, 2) COMMENT '最近1日最终下单金额',
    `order_last_7d_count`                   BIGINT COMMENT '最近7日下单次数',
    `order_activity_last_7d_count`          BIGINT COMMENT '最近7日订单参与活动次数',
    `order_activity_reduce_last_7d_amount`  DECIMAL(16, 2) COMMENT '最近7日订单减免金额(活动)',
    `order_coupon_last_7d_count`            BIGINT COMMENT '最近7日下单用券次数',
    `order_coupon_reduce_last_7d_amount`    DECIMAL(16, 2) COMMENT '最近7日订单减免金额(优惠券)',
    `order_last_7d_original_amount`         DECIMAL(16, 2) COMMENT '最近7日原始下单金额',
    `order_last_7d_final_amount`            DECIMAL(16, 2) COMMENT '最近7日最终下单金额',
    `order_last_30d_count`                  BIGINT COMMENT '最近30日下单次数',
    `order_activity_last_30d_count`         BIGINT COMMENT '最近30日订单参与活动次数',
    `order_activity_reduce_last_30d_amount` DECIMAL(16, 2) COMMENT '最近30日订单减免金额(活动)',
    `order_coupon_last_30d_count`           BIGINT COMMENT '最近30日下单用券次数',
    `order_coupon_reduce_last_30d_amount`   DECIMAL(16, 2) COMMENT '最近30日订单减免金额(优惠券)',
    `order_last_30d_original_amount`        DECIMAL(16, 2) COMMENT '最近30日原始下单金额',
    `order_last_30d_final_amount`           DECIMAL(16, 2) COMMENT '最近30日最终下单金额',
    `order_count`                           BIGINT COMMENT '累积下单次数',
    `order_activity_count`                  BIGINT COMMENT '累积订单参与活动次数',
    `order_activity_reduce_amount`          DECIMAL(16, 2) COMMENT '累积订单减免金额(活动)',
    `order_coupon_count`                    BIGINT COMMENT '累积下单用券次数',
    `order_coupon_reduce_amount`            DECIMAL(16, 2) COMMENT '累积订单减免金额(优惠券)',
    `order_original_amount`                 DECIMAL(16, 2) COMMENT '累积原始下单金额',
    `order_final_amount`                    DECIMAL(16, 2) COMMENT '累积最终下单金额',
    `payment_date_first`                    STRING COMMENT '首次支付时间',
    `payment_date_last`                     STRING COMMENT '末次支付时间',
    `payment_last_1d_count`                 BIGINT COMMENT '最近1日支付次数',
    `payment_last_1d_amount`                DECIMAL(16, 2) COMMENT '最近1日支付金额',
    `payment_last_7d_count`                 BIGINT COMMENT '最近7日支付次数',
    `payment_last_7d_amount`                DECIMAL(16, 2) COMMENT '最近7日支付金额',
    `payment_last_30d_count`                BIGINT COMMENT '最近30日支付次数',
    `payment_last_30d_amount`               DECIMAL(16, 2) COMMENT '最近30日支付金额',
    `payment_count`                         BIGINT COMMENT '累积支付次数',
    `payment_amount`                        DECIMAL(16, 2) COMMENT '累积支付金额',
    `refund_order_last_1d_count`            BIGINT COMMENT '最近1日退单次数',
    `refund_order_last_1d_num`              BIGINT COMMENT '最近1日退单件数',
    `refund_order_last_1d_amount`           DECIMAL(16, 2) COMMENT '最近1日退单金额',
    `refund_order_last_7d_count`            BIGINT COMMENT '最近7日退单次数',
    `refund_order_last_7d_num`              BIGINT COMMENT '最近7日退单件数',
    `refund_order_last_7d_amount`           DECIMAL(16, 2) COMMENT '最近7日退单金额',
    `refund_order_last_30d_count`           BIGINT COMMENT '最近30日退单次数',
    `refund_order_last_30d_num`             BIGINT COMMENT '最近30日退单件数',
    `refund_order_last_30d_amount`          DECIMAL(16, 2) COMMENT '最近30日退单金额',
    `refund_order_count`                    BIGINT COMMENT '累积退单次数',
    `refund_order_num`                      BIGINT COMMENT '累积退单件数',
    `refund_order_amount`                   DECIMAL(16, 2) COMMENT '累积退单金额',
    `refund_payment_last_1d_count`          BIGINT COMMENT '最近1日退款次数',
    `refund_payment_last_1d_num`            BIGINT COMMENT '最近1日退款件数',
    `refund_payment_last_1d_amount`         DECIMAL(16, 2) COMMENT '最近1日退款金额',
    `refund_payment_last_7d_count`          BIGINT COMMENT '最近7日退款次数',
    `refund_payment_last_7d_num`            BIGINT COMMENT '最近7日退款件数',
    `refund_payment_last_7d_amount`         DECIMAL(16, 2) COMMENT '最近7日退款金额',
    `refund_payment_last_30d_count`         BIGINT COMMENT '最近30日退款次数',
    `refund_payment_last_30d_num`           BIGINT COMMENT '最近30日退款件数',
    `refund_payment_last_30d_amount`        DECIMAL(16, 2) COMMENT '最近30日退款金额',
    `refund_payment_count`                  BIGINT COMMENT '累积退款次数',
    `refund_payment_num`                    BIGINT COMMENT '累积退款件数',
    `refund_payment_amount`                 DECIMAL(16, 2) COMMENT '累积退款金额',
    `cart_last_1d_count`                    BIGINT COMMENT '最近1日加入购物车次数',
    `cart_last_7d_count`                    BIGINT COMMENT '最近7日加入购物车次数',
    `cart_last_30d_count`                   BIGINT COMMENT '最近30日加入购物车次数',
    `cart_count`                            BIGINT COMMENT '累积加入购物车次数',
    `favor_last_1d_count`                   BIGINT COMMENT '最近1日收藏次数',
    `favor_last_7d_count`                   BIGINT COMMENT '最近7日收藏次数',
    `favor_last_30d_count`                  BIGINT COMMENT '最近30日收藏次数',
    `favor_count`                           BIGINT COMMENT '累积收藏次数',
    `coupon_last_1d_get_count`              BIGINT COMMENT '最近1日领券次数',
    `coupon_last_1d_using_count`            BIGINT COMMENT '最近1日用券(下单)次数',
    `coupon_last_1d_used_count`             BIGINT COMMENT '最近1日用券(支付)次数',
    `coupon_last_7d_get_count`              BIGINT COMMENT '最近7日领券次数',
    `coupon_last_7d_using_count`            BIGINT COMMENT '最近7日用券(下单)次数',
    `coupon_last_7d_used_count`             BIGINT COMMENT '最近7日用券(支付)次数',
    `coupon_last_30d_get_count`             BIGINT COMMENT '最近30日领券次数',
    `coupon_last_30d_using_count`           BIGINT COMMENT '最近30日用券(下单)次数',
    `coupon_last_30d_used_count`            BIGINT COMMENT '最近30日用券(支付)次数',
    `coupon_get_count`                      BIGINT COMMENT '累积领券次数',
    `coupon_using_count`                    BIGINT COMMENT '累积用券(下单)次数',
    `coupon_used_count`                     BIGINT COMMENT '累积用券(支付)次数',
    `appraise_last_1d_good_count`           BIGINT COMMENT '最近1日好评次数',
    `appraise_last_1d_mid_count`            BIGINT COMMENT '最近1日中评次数',
    `appraise_last_1d_bad_count`            BIGINT COMMENT '最近1日差评次数',
    `appraise_last_1d_default_count`        BIGINT COMMENT '最近1日默认评价次数',
    `appraise_last_7d_good_count`           BIGINT COMMENT '最近7日好评次数',
    `appraise_last_7d_mid_count`            BIGINT COMMENT '最近7日中评次数',
    `appraise_last_7d_bad_count`            BIGINT COMMENT '最近7日差评次数',
    `appraise_last_7d_default_count`        BIGINT COMMENT '最近7日默认评价次数',
    `appraise_last_30d_good_count`          BIGINT COMMENT '最近30日好评次数',
    `appraise_last_30d_mid_count`           BIGINT COMMENT '最近30日中评次数',
    `appraise_last_30d_bad_count`           BIGINT COMMENT '最近30日差评次数',
    `appraise_last_30d_default_count`       BIGINT COMMENT '最近30日默认评价次数',
    `appraise_good_count`                   BIGINT COMMENT '累积好评次数',
    `appraise_mid_count`                    BIGINT COMMENT '累积中评次数',
    `appraise_bad_count`                    BIGINT COMMENT '累积差评次数',
    `appraise_default_count`                BIGINT COMMENT '累积默认评价次数'
    --主要就是对度量值进行1日/7日/30日/累计 进行聚合操作
) COMMENT '会员主题宽表'
    PARTITIONED BY (`dt` STRING)
    STORED AS PARQUET
    LOCATION '/warehouse/gmall/dwt/dwt_user_topic/'
    TBLPROPERTIES ("parquet.compression" = "lzo");


--首日装载
insert overwrite table dwt_user_topic partition (dt = '2021-10-13')
select id,
       login_date_first,--以用户的创建日期作为首次登录日期
       nvl(login_date_last, date_add('2021-10-13', -1)),--若有历史登录记录，则根据历史记录获取末次登录日期，否则统一指定一个日期
       nvl(login_last_1d_count, 0),
       nvl(login_last_1d_day_count, 0),
       nvl(login_last_7d_count, 0),
       nvl(login_last_7d_day_count, 0),
       nvl(login_last_30d_count, 0),
       nvl(login_last_30d_day_count, 0),
       nvl(login_count, 0),
       nvl(login_day_count, 0),
       order_date_first,
       order_date_last,
       nvl(order_last_1d_count, 0),
       nvl(order_activity_last_1d_count, 0),
       nvl(order_activity_reduce_last_1d_amount, 0),
       nvl(order_coupon_last_1d_count, 0),
       nvl(order_coupon_reduce_last_1d_amount, 0),
       nvl(order_last_1d_original_amount, 0),
       nvl(order_last_1d_final_amount, 0),
       nvl(order_last_7d_count, 0),
       nvl(order_activity_last_7d_count, 0),
       nvl(order_activity_reduce_last_7d_amount, 0),
       nvl(order_coupon_last_7d_count, 0),
       nvl(order_coupon_reduce_last_7d_amount, 0),
       nvl(order_last_7d_original_amount, 0),
       nvl(order_last_7d_final_amount, 0),
       nvl(order_last_30d_count, 0),
       nvl(order_activity_last_30d_count, 0),
       nvl(order_activity_reduce_last_30d_amount, 0),
       nvl(order_coupon_last_30d_count, 0),
       nvl(order_coupon_reduce_last_30d_amount, 0),
       nvl(order_last_30d_original_amount, 0),
       nvl(order_last_30d_final_amount, 0),
       nvl(order_count, 0),
       nvl(order_activity_count, 0),
       nvl(order_activity_reduce_amount, 0),
       nvl(order_coupon_count, 0),
       nvl(order_coupon_reduce_amount, 0),
       nvl(order_original_amount, 0),
       nvl(order_final_amount, 0),
       payment_date_first,
       payment_date_last,
       nvl(payment_last_1d_count, 0),
       nvl(payment_last_1d_amount, 0),
       nvl(payment_last_7d_count, 0),
       nvl(payment_last_7d_amount, 0),
       nvl(payment_last_30d_count, 0),
       nvl(payment_last_30d_amount, 0),
       nvl(payment_count, 0),
       nvl(payment_amount, 0),
       nvl(refund_order_last_1d_count, 0),
       nvl(refund_order_last_1d_num, 0),
       nvl(refund_order_last_1d_amount, 0),
       nvl(refund_order_last_7d_count, 0),
       nvl(refund_order_last_7d_num, 0),
       nvl(refund_order_last_7d_amount, 0),
       nvl(refund_order_last_30d_count, 0),
       nvl(refund_order_last_30d_num, 0),
       nvl(refund_order_last_30d_amount, 0),
       nvl(refund_order_count, 0),
       nvl(refund_order_num, 0),
       nvl(refund_order_amount, 0),
       nvl(refund_payment_last_1d_count, 0),
       nvl(refund_payment_last_1d_num, 0),
       nvl(refund_payment_last_1d_amount, 0),
       nvl(refund_payment_last_7d_count, 0),
       nvl(refund_payment_last_7d_num, 0),
       nvl(refund_payment_last_7d_amount, 0),
       nvl(refund_payment_last_30d_count, 0),
       nvl(refund_payment_last_30d_num, 0),
       nvl(refund_payment_last_30d_amount, 0),
       nvl(refund_payment_count, 0),
       nvl(refund_payment_num, 0),
       nvl(refund_payment_amount, 0),
       nvl(cart_last_1d_count, 0),
       nvl(cart_last_7d_count, 0),
       nvl(cart_last_30d_count, 0),
       nvl(cart_count, 0),
       nvl(favor_last_1d_count, 0),
       nvl(favor_last_7d_count, 0),
       nvl(favor_last_30d_count, 0),
       nvl(favor_count, 0),
       nvl(coupon_last_1d_get_count, 0),
       nvl(coupon_last_1d_using_count, 0),
       nvl(coupon_last_1d_used_count, 0),
       nvl(coupon_last_7d_get_count, 0),
       nvl(coupon_last_7d_using_count, 0),
       nvl(coupon_last_7d_used_count, 0),
       nvl(coupon_last_30d_get_count, 0),
       nvl(coupon_last_30d_using_count, 0),
       nvl(coupon_last_30d_used_count, 0),
       nvl(coupon_get_count, 0),
       nvl(coupon_using_count, 0),
       nvl(coupon_used_count, 0),
       nvl(appraise_last_1d_good_count, 0),
       nvl(appraise_last_1d_mid_count, 0),
       nvl(appraise_last_1d_bad_count, 0),
       nvl(appraise_last_1d_default_count, 0),
       nvl(appraise_last_7d_good_count, 0),
       nvl(appraise_last_7d_mid_count, 0),
       nvl(appraise_last_7d_bad_count, 0),
       nvl(appraise_last_7d_default_count, 0),
       nvl(appraise_last_30d_good_count, 0),
       nvl(appraise_last_30d_mid_count, 0),
       nvl(appraise_last_30d_bad_count, 0),
       nvl(appraise_last_30d_default_count, 0),
       nvl(appraise_good_count, 0),
       nvl(appraise_mid_count, 0),
       nvl(appraise_bad_count, 0),
       nvl(appraise_default_count, 0)
from (
         select id,
                date_format(create_time, 'yyyy-MM-dd') login_date_first
         from dim_user_info
         where dt = '9999-99-99'
     ) t1
         left join
     (
         select user_id                                                                       user_id,
                max(dt)                                                                       login_date_last,
                sum(if(dt = '2021-10-13', login_count, 0))                                    login_last_1d_count,
                sum(if(dt = '2021-10-13' and login_count > 0, 1, 0))                          login_last_1d_day_count,
                sum(if(dt >= date_add('2021-10-13', -6), login_count, 0))                     login_last_7d_count,
                sum(if(dt >= date_add('2021-10-13', -6) and login_count > 0, 1, 0))           login_last_7d_day_count,
                sum(if(dt >= date_add('2021-10-13', -29), login_count, 0))                    login_last_30d_count,
                sum(if(dt >= date_add('2021-10-13', -29) and login_count > 0, 1, 0))          login_last_30d_day_count,
                sum(login_count)                                                              login_count,
                sum(if(login_count > 0, 1, 0))                                                login_day_count,
                min(if(order_count > 0, dt, null))                                            order_date_first,
                max(if(order_count > 0, dt, null))                                            order_date_last,
                sum(if(dt = '2021-10-13', order_count, 0))                                    order_last_1d_count,
                sum(if(dt = '2021-10-13', order_activity_count, 0))                           order_activity_last_1d_count,
                sum(if(dt = '2021-10-13', order_activity_reduce_amount, 0))                   order_activity_reduce_last_1d_amount,
                sum(if(dt = '2021-10-13', order_coupon_count, 0))                             order_coupon_last_1d_count,
                sum(if(dt = '2021-10-13', order_coupon_reduce_amount, 0))                     order_coupon_reduce_last_1d_amount,
                sum(if(dt = '2021-10-13', order_original_amount, 0))                          order_last_1d_original_amount,
                sum(if(dt = '2021-10-13', order_final_amount, 0))                             order_last_1d_final_amount,
                sum(if(dt >= date_add('2021-10-13', -6), order_count, 0))                     order_last_7d_count,
                sum(if(dt >= date_add('2021-10-13', -6), order_activity_count, 0))            order_activity_last_7d_count,
                sum(if(dt >= date_add('2021-10-13', -6), order_activity_reduce_amount,
                       0))                                                                    order_activity_reduce_last_7d_amount,
                sum(if(dt >= date_add('2021-10-13', -6), order_coupon_count, 0))              order_coupon_last_7d_count,
                sum(
                        if(dt >= date_add('2021-10-13', -6), order_coupon_reduce_amount, 0))  order_coupon_reduce_last_7d_amount,
                sum(
                        if(dt >= date_add('2021-10-13', -6), order_original_amount, 0))       order_last_7d_original_amount,
                sum(if(dt >= date_add('2021-10-13', -6), order_final_amount, 0))              order_last_7d_final_amount,
                sum(if(dt >= date_add('2021-10-13', -29), order_count, 0))                    order_last_30d_count,
                sum(
                        if(dt >= date_add('2021-10-13', -29), order_activity_count, 0))       order_activity_last_30d_count,
                sum(if(dt >= date_add('2021-10-13', -29), order_activity_reduce_amount,
                       0))                                                                    order_activity_reduce_last_30d_amount,
                sum(if(dt >= date_add('2021-10-13', -29), order_coupon_count, 0))             order_coupon_last_30d_count,
                sum(
                        if(dt >= date_add('2021-10-13', -29), order_coupon_reduce_amount, 0)) order_coupon_reduce_last_30d_amount,
                sum(
                        if(dt >= date_add('2021-10-13', -29), order_original_amount, 0))      order_last_30d_original_amount,
                sum(if(dt >= date_add('2021-10-13', -29), order_final_amount, 0))             order_last_30d_final_amount,
                sum(order_count)                                                              order_count,
                sum(order_activity_count)                                                     order_activity_count,
                sum(order_activity_reduce_amount)                                             order_activity_reduce_amount,
                sum(order_coupon_count)                                                       order_coupon_count,
                sum(order_coupon_reduce_amount)                                               order_coupon_reduce_amount,
                sum(order_original_amount)                                                    order_original_amount,
                sum(order_final_amount)                                                       order_final_amount,
                min(if(payment_count > 0, dt, null))                                          payment_date_first,
                max(if(payment_count > 0, dt, null))                                          payment_date_last,
                sum(if(dt = '2021-10-13', payment_count, 0))                                  payment_last_1d_count,
                sum(if(dt = '2021-10-13', payment_amount, 0))                                 payment_last_1d_amount,
                sum(if(dt >= date_add('2021-10-13', -6), payment_count, 0))                   payment_last_7d_count,
                sum(if(dt >= date_add('2021-10-13', -6), payment_amount, 0))                  payment_last_7d_amount,
                sum(if(dt >= date_add('2021-10-13', -29), payment_count, 0))                  payment_last_30d_count,
                sum(if(dt >= date_add('2021-10-13', -29), payment_amount, 0))                 payment_last_30d_amount,
                sum(payment_count)                                                            payment_count,
                sum(payment_amount)                                                           payment_amount,
                sum(if(dt = '2021-10-13', refund_order_count, 0))                             refund_order_last_1d_count,
                sum(if(dt = '2021-10-13', refund_order_num, 0))                               refund_order_last_1d_num,
                sum(if(dt = '2021-10-13', refund_order_amount, 0))                            refund_order_last_1d_amount,
                sum(if(dt >= date_add('2021-10-13', -6), refund_order_count, 0))              refund_order_last_7d_count,
                sum(if(dt >= date_add('2021-10-13', -6), refund_order_num, 0))                refund_order_last_7d_num,
                sum(if(dt >= date_add('2021-10-13', -6), refund_order_amount, 0))             refund_order_last_7d_amount,
                sum(if(dt >= date_add('2021-10-13', -29), refund_order_count, 0))             refund_order_last_30d_count,
                sum(if(dt >= date_add('2021-10-13', -29), refund_order_num, 0))               refund_order_last_30d_num,
                sum(if(dt >= date_add('2021-10-13', -29), refund_order_amount, 0))            refund_order_last_30d_amount,
                sum(refund_order_count)                                                       refund_order_count,
                sum(refund_order_num)                                                         refund_order_num,
                sum(refund_order_amount)                                                      refund_order_amount,
                sum(if(dt = '2021-10-13', refund_payment_count, 0))                           refund_payment_last_1d_count,
                sum(if(dt = '2021-10-13', refund_payment_num, 0))                             refund_payment_last_1d_num,
                sum(if(dt = '2021-10-13', refund_payment_amount, 0))                          refund_payment_last_1d_amount,
                sum(if(dt >= date_add('2021-10-13', -6), refund_payment_count, 0))            refund_payment_last_7d_count,
                sum(if(dt >= date_add('2021-10-13', -6), refund_payment_num, 0))              refund_payment_last_7d_num,
                sum(
                        if(dt >= date_add('2021-10-13', -6), refund_payment_amount, 0))       refund_payment_last_7d_amount,
                sum(
                        if(dt >= date_add('2021-10-13', -29), refund_payment_count, 0))       refund_payment_last_30d_count,
                sum(if(dt >= date_add('2021-10-13', -29), refund_payment_num, 0))             refund_payment_last_30d_num,
                sum(
                        if(dt >= date_add('2021-10-13', -29), refund_payment_amount, 0))      refund_payment_last_30d_amount,
                sum(refund_payment_count)                                                     refund_payment_count,
                sum(refund_payment_num)                                                       refund_payment_num,
                sum(refund_payment_amount)                                                    refund_payment_amount,
                sum(if(dt = '2021-10-13', cart_count, 0))                                     cart_last_1d_count,
                sum(if(dt >= date_add('2021-10-13', -6), cart_count, 0))                      cart_last_7d_count,
                sum(if(dt >= date_add('2021-10-13', -29), cart_count, 0))                     cart_last_30d_count,
                sum(cart_count)                                                               cart_count,
                sum(if(dt = '2021-10-13', favor_count, 0))                                    favor_last_1d_count,
                sum(if(dt >= date_add('2021-10-13', -6), favor_count, 0))                     favor_last_7d_count,
                sum(if(dt >= date_add('2021-10-13', -29), favor_count, 0))                    favor_last_30d_count,
                sum(favor_count)                                                              favor_count,
                sum(if(dt = '2021-10-13', coupon_get_count, 0))                               coupon_last_1d_get_count,
                sum(if(dt = '2021-10-13', coupon_using_count, 0))                             coupon_last_1d_using_count,
                sum(if(dt = '2021-10-13', coupon_used_count, 0))                              coupon_last_1d_used_count,
                sum(if(dt >= date_add('2021-10-13', -6), coupon_get_count, 0))                coupon_last_7d_get_count,
                sum(if(dt >= date_add('2021-10-13', -6), coupon_using_count, 0))              coupon_last_7d_using_count,
                sum(if(dt >= date_add('2021-10-13', -6), coupon_used_count, 0))               coupon_last_7d_used_count,
                sum(if(dt >= date_add('2021-10-13', -29), coupon_get_count, 0))               coupon_last_30d_get_count,
                sum(if(dt >= date_add('2021-10-13', -29), coupon_using_count, 0))             coupon_last_30d_using_count,
                sum(if(dt >= date_add('2021-10-13', -29), coupon_used_count, 0))              coupon_last_30d_used_count,
                sum(coupon_get_count)                                                         coupon_get_count,
                sum(coupon_using_count)                                                       coupon_using_count,
                sum(coupon_used_count)                                                        coupon_used_count,
                sum(if(dt = '2021-10-13', appraise_good_count, 0))                            appraise_last_1d_good_count,
                sum(if(dt = '2021-10-13', appraise_mid_count, 0))                             appraise_last_1d_mid_count,
                sum(if(dt = '2021-10-13', appraise_bad_count, 0))                             appraise_last_1d_bad_count,
                sum(if(dt = '2021-10-13', appraise_default_count, 0))                         appraise_last_1d_default_count,
                sum(if(dt >= date_add('2021-10-13', -6), appraise_good_count, 0))             appraise_last_7d_good_count,
                sum(if(dt >= date_add('2021-10-13', -6), appraise_mid_count, 0))              appraise_last_7d_mid_count,
                sum(if(dt >= date_add('2021-10-13', -6), appraise_bad_count, 0))              appraise_last_7d_bad_count,
                sum(
                        if(dt >= date_add('2021-10-13', -6), appraise_default_count, 0))      appraise_last_7d_default_count,
                sum(if(dt >= date_add('2021-10-13', -29), appraise_good_count, 0))            appraise_last_30d_good_count,
                sum(if(dt >= date_add('2021-10-13', -29), appraise_mid_count, 0))             appraise_last_30d_mid_count,
                sum(if(dt >= date_add('2021-10-13', -29), appraise_bad_count, 0))             appraise_last_30d_bad_count,
                sum(
                        if(dt >= date_add('2021-10-13', -29), appraise_default_count, 0))     appraise_last_30d_default_count,
                sum(appraise_good_count)                                                      appraise_good_count,
                sum(appraise_mid_count)                                                       appraise_mid_count,
                sum(appraise_bad_count)                                                       appraise_bad_count,
                sum(appraise_default_count)                                                   appraise_default_count
         from dws_user_action_daycount
         group by user_id
     ) t2
     on t1.id = t2.user_id;


--每日装载
insert overwrite table dwt_user_topic partition (dt = '2021-10-14')
select nvl(1d_ago.user_id, old.user_id),
       nvl(old.login_date_first, '2021-10-14'),
       if(1d_ago.user_id is not null, '2021-10-14', old.login_date_last),
       nvl(1d_ago.login_count, 0),
       if(1d_ago.user_id is not null, 1, 0),
       nvl(old.login_last_7d_count, 0) + nvl(1d_ago.login_count, 0) - nvl(7d_ago.login_count, 0),
       nvl(old.login_last_7d_day_count, 0) + if(1d_ago.user_id is null, 0, 1) - if(7d_ago.user_id is null, 0, 1),
       nvl(old.login_last_30d_count, 0) + nvl(1d_ago.login_count, 0) - nvl(30d_ago.login_count, 0),
       nvl(old.login_last_30d_day_count, 0) + if(1d_ago.user_id is null, 0, 1) - if(30d_ago.user_id is null, 0, 1),
       nvl(old.login_count, 0) + nvl(1d_ago.login_count, 0),
       nvl(old.login_day_count, 0) + if(1d_ago.user_id is not null, 1, 0),
       if(old.order_date_first is null and 1d_ago.order_count > 0, '2021-10-14', old.order_date_first),
       if(1d_ago.order_count > 0, '2021-10-14', old.order_date_last),
       nvl(1d_ago.order_count, 0),
       nvl(1d_ago.order_activity_count, 0),
       nvl(1d_ago.order_activity_reduce_amount, 0.0),
       nvl(1d_ago.order_coupon_count, 0),
       nvl(1d_ago.order_coupon_reduce_amount, 0.0),
       nvl(1d_ago.order_original_amount, 0.0),
       nvl(1d_ago.order_final_amount, 0.0),
       nvl(old.order_last_7d_count, 0) + nvl(1d_ago.order_count, 0) - nvl(7d_ago.order_count, 0),
       nvl(old.order_activity_last_7d_count, 0) + nvl(1d_ago.order_activity_count, 0) -
       nvl(7d_ago.order_activity_count, 0),
       nvl(old.order_activity_reduce_last_7d_amount, 0.0) + nvl(1d_ago.order_activity_reduce_amount, 0.0) -
       nvl(7d_ago.order_activity_reduce_amount, 0.0),
       nvl(old.order_coupon_last_7d_count, 0) + nvl(1d_ago.order_coupon_count, 0) - nvl(7d_ago.order_coupon_count, 0),
       nvl(old.order_coupon_reduce_last_7d_amount, 0.0) + nvl(1d_ago.order_coupon_reduce_amount, 0.0) -
       nvl(7d_ago.order_coupon_reduce_amount, 0.0),
       nvl(old.order_last_7d_original_amount, 0.0) + nvl(1d_ago.order_original_amount, 0.0) -
       nvl(7d_ago.order_original_amount, 0.0),
       nvl(old.order_last_7d_final_amount, 0.0) + nvl(1d_ago.order_final_amount, 0.0) -
       nvl(7d_ago.order_final_amount, 0.0),
       nvl(old.order_last_30d_count, 0) + nvl(1d_ago.order_count, 0) - nvl(30d_ago.order_count, 0),
       nvl(old.order_activity_last_30d_count, 0) + nvl(1d_ago.order_activity_count, 0) -
       nvl(30d_ago.order_activity_count, 0),
       nvl(old.order_activity_reduce_last_30d_amount, 0.0) + nvl(1d_ago.order_activity_reduce_amount, 0.0) -
       nvl(30d_ago.order_activity_reduce_amount, 0.0),
       nvl(old.order_coupon_last_30d_count, 0) + nvl(1d_ago.order_coupon_count, 0) - nvl(30d_ago.order_coupon_count, 0),
       nvl(old.order_coupon_reduce_last_30d_amount, 0.0) + nvl(1d_ago.order_coupon_reduce_amount, 0.0) -
       nvl(30d_ago.order_coupon_reduce_amount, 0.0),
       nvl(old.order_last_30d_original_amount, 0.0) + nvl(1d_ago.order_original_amount, 0.0) -
       nvl(30d_ago.order_original_amount, 0.0),
       nvl(old.order_last_30d_final_amount, 0.0) + nvl(1d_ago.order_final_amount, 0.0) -
       nvl(30d_ago.order_final_amount, 0.0),
       nvl(old.order_count, 0) + nvl(1d_ago.order_count, 0),
       nvl(old.order_activity_count, 0) + nvl(1d_ago.order_activity_count, 0),
       nvl(old.order_activity_reduce_amount, 0.0) + nvl(1d_ago.order_activity_reduce_amount, 0.0),
       nvl(old.order_coupon_count, 0) + nvl(1d_ago.order_coupon_count, 0),
       nvl(old.order_coupon_reduce_amount, 0.0) + nvl(1d_ago.order_coupon_reduce_amount, 0.0),
       nvl(old.order_original_amount, 0.0) + nvl(1d_ago.order_original_amount, 0.0),
       nvl(old.order_final_amount, 0.0) + nvl(1d_ago.order_final_amount, 0.0),
       if(old.payment_date_first is null and 1d_ago.payment_count > 0, '2021-10-14', old.payment_date_first),
       if(1d_ago.payment_count > 0, '2021-10-14', old.payment_date_last),
       nvl(1d_ago.payment_count, 0),
       nvl(1d_ago.payment_amount, 0.0),
       nvl(old.payment_last_7d_count, 0) + nvl(1d_ago.payment_count, 0) - nvl(7d_ago.payment_count, 0),
       nvl(old.payment_last_7d_amount, 0.0) + nvl(1d_ago.payment_amount, 0.0) - nvl(7d_ago.payment_amount, 0.0),
       nvl(old.payment_last_30d_count, 0) + nvl(1d_ago.payment_count, 0) - nvl(30d_ago.payment_count, 0),
       nvl(old.payment_last_30d_amount, 0.0) + nvl(1d_ago.payment_amount, 0.0) - nvl(30d_ago.payment_amount, 0.0),
       nvl(old.payment_count, 0) + nvl(1d_ago.payment_count, 0),
       nvl(old.payment_amount, 0.0) + nvl(1d_ago.payment_amount, 0.0),
       nvl(1d_ago.refund_order_count, 0),
       nvl(1d_ago.refund_order_num, 0),
       nvl(1d_ago.refund_order_amount, 0.0),
       nvl(old.refund_order_last_7d_count, 0) + nvl(1d_ago.refund_order_count, 0) - nvl(7d_ago.refund_order_count, 0),
       nvl(old.refund_order_last_7d_num, 0) + nvl(1d_ago.refund_order_num, 0) - nvl(7d_ago.refund_order_num, 0),
       nvl(old.refund_order_last_7d_amount, 0.0) + nvl(1d_ago.refund_order_amount, 0.0) -
       nvl(7d_ago.refund_order_amount, 0.0),
       nvl(old.refund_order_last_30d_count, 0) + nvl(1d_ago.refund_order_count, 0) - nvl(30d_ago.refund_order_count, 0),
       nvl(old.refund_order_last_30d_num, 0) + nvl(1d_ago.refund_order_num, 0) - nvl(30d_ago.refund_order_num, 0),
       nvl(old.refund_order_last_30d_amount, 0.0) + nvl(1d_ago.refund_order_amount, 0.0) -
       nvl(30d_ago.refund_order_amount, 0.0),
       nvl(old.refund_order_count, 0) + nvl(1d_ago.refund_order_count, 0),
       nvl(old.refund_order_num, 0) + nvl(1d_ago.refund_order_num, 0),
       nvl(old.refund_order_amount, 0.0) + nvl(1d_ago.refund_order_amount, 0.0),
       nvl(1d_ago.refund_payment_count, 0),
       nvl(1d_ago.refund_payment_num, 0),
       nvl(1d_ago.refund_payment_amount, 0.0),
       nvl(old.refund_payment_last_7d_count, 0) + nvl(1d_ago.refund_payment_count, 0) -
       nvl(7d_ago.refund_payment_count, 0),
       nvl(old.refund_payment_last_7d_num, 0) + nvl(1d_ago.refund_payment_num, 0) - nvl(7d_ago.refund_payment_num, 0),
       nvl(old.refund_payment_last_7d_amount, 0.0) + nvl(1d_ago.refund_payment_amount, 0.0) -
       nvl(7d_ago.refund_payment_amount, 0.0),
       nvl(old.refund_payment_last_30d_count, 0) + nvl(1d_ago.refund_payment_count, 0) -
       nvl(30d_ago.refund_payment_count, 0),
       nvl(old.refund_payment_last_30d_num, 0) + nvl(1d_ago.refund_payment_num, 0) - nvl(30d_ago.refund_payment_num, 0),
       nvl(old.refund_payment_last_30d_amount, 0.0) + nvl(1d_ago.refund_payment_amount, 0.0) -
       nvl(30d_ago.refund_payment_amount, 0.0),
       nvl(old.refund_payment_count, 0) + nvl(1d_ago.refund_payment_count, 0),
       nvl(old.refund_payment_num, 0) + nvl(1d_ago.refund_payment_num, 0),
       nvl(old.refund_payment_amount, 0.0) + nvl(1d_ago.refund_payment_amount, 0.0),
       nvl(1d_ago.cart_count, 0),
       nvl(old.cart_last_7d_count, 0) + nvl(1d_ago.cart_count, 0) - nvl(7d_ago.cart_count, 0),
       nvl(old.cart_last_30d_count, 0) + nvl(1d_ago.cart_count, 0) - nvl(30d_ago.cart_count, 0),
       nvl(old.cart_count, 0) + nvl(1d_ago.cart_count, 0),
       nvl(1d_ago.favor_count, 0),
       nvl(old.favor_last_7d_count, 0) + nvl(1d_ago.favor_count, 0) - nvl(7d_ago.favor_count, 0),
       nvl(old.favor_last_30d_count, 0) + nvl(1d_ago.favor_count, 0) - nvl(30d_ago.favor_count, 0),
       nvl(old.favor_count, 0) + nvl(1d_ago.favor_count, 0),
       nvl(1d_ago.coupon_get_count, 0),
       nvl(1d_ago.coupon_using_count, 0),
       nvl(1d_ago.coupon_used_count, 0),
       nvl(old.coupon_last_7d_get_count, 0) + nvl(1d_ago.coupon_get_count, 0) - nvl(7d_ago.coupon_get_count, 0),
       nvl(old.coupon_last_7d_using_count, 0) + nvl(1d_ago.coupon_using_count, 0) - nvl(7d_ago.coupon_using_count, 0),
       nvl(old.coupon_last_7d_used_count, 0) + nvl(1d_ago.coupon_used_count, 0) - nvl(7d_ago.coupon_used_count, 0),
       nvl(old.coupon_last_30d_get_count, 0) + nvl(1d_ago.coupon_get_count, 0) - nvl(30d_ago.coupon_get_count, 0),
       nvl(old.coupon_last_30d_using_count, 0) + nvl(1d_ago.coupon_using_count, 0) - nvl(30d_ago.coupon_using_count, 0),
       nvl(old.coupon_last_30d_used_count, 0) + nvl(1d_ago.coupon_used_count, 0) - nvl(30d_ago.coupon_used_count, 0),
       nvl(old.coupon_get_count, 0) + nvl(1d_ago.coupon_get_count, 0),
       nvl(old.coupon_using_count, 0) + nvl(1d_ago.coupon_using_count, 0),
       nvl(old.coupon_used_count, 0) + nvl(1d_ago.coupon_used_count, 0),
       nvl(1d_ago.appraise_good_count, 0),
       nvl(1d_ago.appraise_mid_count, 0),
       nvl(1d_ago.appraise_bad_count, 0),
       nvl(1d_ago.appraise_default_count, 0),
       nvl(old.appraise_last_7d_good_count, 0) + nvl(1d_ago.appraise_good_count, 0) -
       nvl(7d_ago.appraise_good_count, 0),
       nvl(old.appraise_last_7d_mid_count, 0) + nvl(1d_ago.appraise_mid_count, 0) - nvl(7d_ago.appraise_mid_count, 0),
       nvl(old.appraise_last_7d_bad_count, 0) + nvl(1d_ago.appraise_bad_count, 0) - nvl(7d_ago.appraise_bad_count, 0),
       nvl(old.appraise_last_7d_default_count, 0) + nvl(1d_ago.appraise_default_count, 0) -
       nvl(7d_ago.appraise_default_count, 0),
       nvl(old.appraise_last_30d_good_count, 0) + nvl(1d_ago.appraise_good_count, 0) -
       nvl(30d_ago.appraise_good_count, 0),
       nvl(old.appraise_last_30d_mid_count, 0) + nvl(1d_ago.appraise_mid_count, 0) - nvl(30d_ago.appraise_mid_count, 0),
       nvl(old.appraise_last_30d_bad_count, 0) + nvl(1d_ago.appraise_bad_count, 0) - nvl(30d_ago.appraise_bad_count, 0),
       nvl(old.appraise_last_30d_default_count, 0) + nvl(1d_ago.appraise_default_count, 0) -
       nvl(30d_ago.appraise_default_count, 0),
       nvl(old.appraise_good_count, 0) + nvl(1d_ago.appraise_good_count, 0),
       nvl(old.appraise_mid_count, 0) + nvl(1d_ago.appraise_mid_count, 0),
       nvl(old.appraise_bad_count, 0) + nvl(1d_ago.appraise_bad_count, 0),
       nvl(old.appraise_default_count, 0) + nvl(1d_ago.appraise_default_count, 0)
from (
         select user_id,
                login_date_first,
                login_date_last,
                login_date_1d_count,
                login_last_1d_day_count,
                login_last_7d_count,
                login_last_7d_day_count,
                login_last_30d_count,
                login_last_30d_day_count,
                login_count,
                login_day_count,
                order_date_first,
                order_date_last,
                order_last_1d_count,
                order_activity_last_1d_count,
                order_activity_reduce_last_1d_amount,
                order_coupon_last_1d_count,
                order_coupon_reduce_last_1d_amount,
                order_last_1d_original_amount,
                order_last_1d_final_amount,
                order_last_7d_count,
                order_activity_last_7d_count,
                order_activity_reduce_last_7d_amount,
                order_coupon_last_7d_count,
                order_coupon_reduce_last_7d_amount,
                order_last_7d_original_amount,
                order_last_7d_final_amount,
                order_last_30d_count,
                order_activity_last_30d_count,
                order_activity_reduce_last_30d_amount,
                order_coupon_last_30d_count,
                order_coupon_reduce_last_30d_amount,
                order_last_30d_original_amount,
                order_last_30d_final_amount,
                order_count,
                order_activity_count,
                order_activity_reduce_amount,
                order_coupon_count,
                order_coupon_reduce_amount,
                order_original_amount,
                order_final_amount,
                payment_date_first,
                payment_date_last,
                payment_last_1d_count,
                payment_last_1d_amount,
                payment_last_7d_count,
                payment_last_7d_amount,
                payment_last_30d_count,
                payment_last_30d_amount,
                payment_count,
                payment_amount,
                refund_order_last_1d_count,
                refund_order_last_1d_num,
                refund_order_last_1d_amount,
                refund_order_last_7d_count,
                refund_order_last_7d_num,
                refund_order_last_7d_amount,
                refund_order_last_30d_count,
                refund_order_last_30d_num,
                refund_order_last_30d_amount,
                refund_order_count,
                refund_order_num,
                refund_order_amount,
                refund_payment_last_1d_count,
                refund_payment_last_1d_num,
                refund_payment_last_1d_amount,
                refund_payment_last_7d_count,
                refund_payment_last_7d_num,
                refund_payment_last_7d_amount,
                refund_payment_last_30d_count,
                refund_payment_last_30d_num,
                refund_payment_last_30d_amount,
                refund_payment_count,
                refund_payment_num,
                refund_payment_amount,
                cart_last_1d_count,
                cart_last_7d_count,
                cart_last_30d_count,
                cart_count,
                favor_last_1d_count,
                favor_last_7d_count,
                favor_last_30d_count,
                favor_count,
                coupon_last_1d_get_count,
                coupon_last_1d_using_count,
                coupon_last_1d_used_count,
                coupon_last_7d_get_count,
                coupon_last_7d_using_count,
                coupon_last_7d_used_count,
                coupon_last_30d_get_count,
                coupon_last_30d_using_count,
                coupon_last_30d_used_count,
                coupon_get_count,
                coupon_using_count,
                coupon_used_count,
                appraise_last_1d_good_count,
                appraise_last_1d_mid_count,
                appraise_last_1d_bad_count,
                appraise_last_1d_default_count,
                appraise_last_7d_good_count,
                appraise_last_7d_mid_count,
                appraise_last_7d_bad_count,
                appraise_last_7d_default_count,
                appraise_last_30d_good_count,
                appraise_last_30d_mid_count,
                appraise_last_30d_bad_count,
                appraise_last_30d_default_count,
                appraise_good_count,
                appraise_mid_count,
                appraise_bad_count,
                appraise_default_count
         from dwt_user_topic
         where dt = date_add('2021-10-14', -1)
     ) old
         full outer join
     (
         select user_id,
                login_count,
                cart_count,
                favor_count,
                order_count,
                order_activity_count,
                order_activity_reduce_amount,
                order_coupon_count,
                order_coupon_reduce_amount,
                order_original_amount,
                order_final_amount,
                payment_count,
                payment_amount,
                refund_order_count,
                refund_order_num,
                refund_order_amount,
                refund_payment_count,
                refund_payment_num,
                refund_payment_amount,
                coupon_get_count,
                coupon_using_count,
                coupon_used_count,
                appraise_good_count,
                appraise_mid_count,
                appraise_bad_count,
                appraise_default_count
         from dws_user_action_daycount
         where dt = '2021-10-14'
     ) 1d_ago
     on old.user_id = 1d_ago.user_id
         left join
     (
         select user_id,
                login_count,
                cart_count,
                favor_count,
                order_count,
                order_activity_count,
                order_activity_reduce_amount,
                order_coupon_count,
                order_coupon_reduce_amount,
                order_original_amount,
                order_final_amount,
                payment_count,
                payment_amount,
                refund_order_count,
                refund_order_num,
                refund_order_amount,
                refund_payment_count,
                refund_payment_num,
                refund_payment_amount,
                coupon_get_count,
                coupon_using_count,
                coupon_used_count,
                appraise_good_count,
                appraise_mid_count,
                appraise_bad_count,
                appraise_default_count
         from dws_user_action_daycount
         where dt = date_add('2021-10-14', -7)
     ) 7d_ago
     on old.user_id = 7d_ago.user_id
         left join
     (
         select user_id,
                login_count,
                cart_count,
                favor_count,
                order_count,
                order_activity_count,
                order_activity_reduce_amount,
                order_coupon_count,
                order_coupon_reduce_amount,
                order_original_amount,
                order_final_amount,
                payment_count,
                payment_amount,
                refund_order_count,
                refund_order_num,
                refund_order_amount,
                refund_payment_count,
                refund_payment_num,
                refund_payment_amount,
                coupon_get_count,
                coupon_using_count,
                coupon_used_count,
                appraise_good_count,
                appraise_mid_count,
                appraise_bad_count,
                appraise_default_count
         from dws_user_action_daycount
         where dt = date_add('2021-10-14', -30)
     ) 30d_ago
     on old.user_id = 30d_ago.user_id;
